'use strict'

// 📐 eslint: https://eslint.org/docs/rules/
module.exports = {
  rules: {
    'accessor-pairs': 'error',
    // 'array-bracket-newline': 'off',
    'array-bracket-spacing': ['error', 'never'], // ✘ disabled by eslint-config-prettier
    'array-callback-return': 'error',
    // 'array-element-newline': 'off',
    'arrow-body-style': 'error', // ✘ disabled by eslint-config-prettier
    // 'arrow-parens': 'off',
    // 'arrow-spacing': 'off',
    // 'block-scoped-var': 'off',
    // 'block-spacing': 'off',
    'brace-style': ['error', '1tbs', { allowSingleLine: true }], // ✘ disabled by eslint-config-prettier
    // 'callback-return': 'off',
    camelcase: ['error', { allow: ['^UNSAFE_'], properties: 'never' }],
    // 'capitalized-comments': 'off',
    // 'class-methods-use-this': 'off',
    // 'comma-dangle': 'off',
    'comma-spacing': ['error', { before: false, after: true }], // ✘ disabled by eslint-config-prettier
    'comma-style': ['error', 'last'], // ✘ disabled by eslint-config-prettier
    complexity: 'warn',
    'computed-property-spacing': 'error', // ✘ disabled by eslint-config-prettier
    'consistent-return': 'error',
    // 'consistent-this': 'off',
    'constructor-super': 'error',
    curly: ['error', 'multi-line'], // ✘ disabled by eslint-config-prettier
    'default-case': 'error',
    // 'default-param-last': 'off',
    'dot-location': ['error', 'property'], // ✘ disabled by eslint-config-prettier
    'dot-notation': 'error',
    'eol-last': 'error', // ✘ disabled by eslint-config-prettier
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'for-direction': 'error',
    'func-call-spacing': 'error', // ✘ disabled by eslint-config-prettier
    // 'func-name-matching': 'off',
    'func-names': ['warn', 'as-needed'],
    // 'func-style': 'off',
    // 'function-call-argument-newline': 'off',
    // 'function-paren-newline': 'off',
    // 'generator-star-spacing': 'off',
    'getter-return': 'error',
    // 'global-require': 'off',
    'guard-for-in': 'error',
    'handle-callback-err': ['error', '^(err|error)$'],
    // 'id-blacklist': 'off',
    // 'id-length': 'off',
    // 'id-match': 'off',
    // 'implicit-arrow-linebreak': 'off',
    // 'indent': 'off',
    // 'init-declarations': 'off',
    'jsx-quotes': ['error', 'prefer-single'], // ✘ disabled by eslint-config-prettier
    'key-spacing': 'error', // ✘ disabled by eslint-config-prettier
    'keyword-spacing': 'error', // ✘ disabled by eslint-config-prettier
    // 'line-comment-position': 'off',
    // 'linebreak-style': 'off',
    // 'lines-around-comment': 'off',
    'lines-between-class-members': 'error',
    'max-classes-per-file': ['error', 1],
    'max-depth': 'warn',
    // 'max-len': 'off',
    'max-lines': 'warn',
    'max-lines-per-function': 'warn',
    'max-nested-callbacks': 'warn',
    'max-params': 'warn',
    // 'max-statements': 'off',
    'max-statements-per-line': 'warn',
    // 'multiline-comment-style': 'off',
    // 'multiline-ternary': 'off',
    'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
    'new-parens': 'error', // ✘ disabled by eslint-config-prettier
    // 'newline-per-chained-call': 'off',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'error',
    'no-bitwise': 'error',
    'no-buffer-constructor': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-confusing-arrow': 'error', // ✘ disabled by eslint-config-prettier
    'no-console': 'warn',
    'no-const-assign': 'error',
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-continue': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    // 'no-div-regex': '',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': ['error', { includeExports: true }],
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-function': 'error',
    'no-empty-pattern': 'error',
    // 'no-eq-null': 'off',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-label': 'error',
    // 'no-extra-parens': 'off',
    'no-extra-semi': 'error', // ✘ disabled by eslint-config-prettier
    'no-fallthrough': 'error',
    'no-floating-decimal': 'error', // ✘ disabled by eslint-config-prettier
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    // 'no-implicit-coercion': 'off',
    // 'no-implicit-globals': 'off',
    'no-implied-eval': 'error',
    'no-import-assign': 'error',
    // 'no-inline-comments': 'off',
    'no-inner-declarations': ['error', 'functions'],
    'no-invalid-regexp': 'error',
    'no-invalid-this': 'error',
    'no-irregular-whitespace': 'error',
    // 'no-iterator': 'off',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    // 'no-magic-numbers': 'off',
    'no-misleading-character-class': 'error',
    'no-mixed-operators': 'error', // ✘ disabled by eslint-config-prettier
    // 'no-mixed-requires': 'off',
    'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'], // ✘ disabled by eslint-config-prettier
    'no-multi-assign': 'error',
    'no-multi-spaces': 'error', // ✘ disabled by eslint-config-prettier
    'no-multi-str': 'error',
    'no-multiple-empty-lines': ['error', { max: 1 }], // ✘ disabled by eslint-config-prettier
    // 'no-negated-condition': 'off',
    // 'no-nested-ternary': 'off',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-symbol': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    // 'no-param-reassign': 'off',
    'no-path-concat': 'error',
    // 'no-plusplus': 'off',
    // 'no-process-env': 'off',
    'no-process-exit': 'warn',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    // 'no-restricted-globals': 'off',
    // 'no-restricted-imports': 'off',
    // 'no-restricted-modules': 'off',
    // 'no-restricted-properties': 'off',
    'no-restricted-syntax': [
      'error',
      {
        selector: 'SequenceExpression',
        message: 'Unexpected use of comma operator.',
      },
    ],
    'no-return-assign': ['error', 'except-parens'],
    'no-return-await': 'error',
    'no-script-url': 'warn',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    // 'no-sequences': 'error',
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    // 'no-sync': 'off',
    // 'no-tabs': 'off',
    'no-template-curly-in-string': 'error',
    // 'no-ternary': 'off',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error', // ✘ disabled by eslint-config-prettier
    'no-undef': 'error',
    'no-undef-init': 'error',
    // 'no-undefined': 'off',
    // 'no-underscore-dangle': 'off',
    'no-unexpected-multiline': 'error', // ✘ disabled by eslint-config-prettier
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
      },
    ],
    'no-unused-labels': 'error',
    'no-unused-vars': ['error', { ignoreRestSiblings: true }],
    'no-use-before-define': ['error', { functions: false }],
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-warning-comments': ['warn', { location: 'anywhere' }],
    'no-whitespace-before-property': 'error', // ✘ disabled by eslint-config-prettier
    'no-with': 'error',
    // 'nonblock-statement-body-position': 'off',
    // 'object-curly-newline': 'off',
    'object-curly-spacing': ['error', 'always'], // ✘ disabled by eslint-config-prettier
    // 'object-property-newline': 'off',
    'object-shorthand': ['error', 'always', { avoidQuotes: true }],
    'one-var': ['error', { initialized: 'never' }],
    // 'one-var-declaration-per-line': 'off',
    'operator-assignment': 'error',
    // 'operator-linebreak': 'off',
    'padded-blocks': ['error', 'never'], // ✘ disabled by eslint-config-prettier
    // 'padding-line-between-statements': 'off',
    // 'prefer-arrow-callback': 'off',
    'prefer-const': ['error', { destructuring: 'all' }],
    // 'prefer-destructuring': 'off',
    // 'prefer-named-capture-group': 'off',
    'prefer-numeric-literals': 'error',
    // 'prefer-object-spread': 'off',
    'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
    'prefer-regex-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'quote-props': ['error', 'as-needed'], // ✘ disabled by eslint-config-prettier
    quotes: ['error', 'single', { avoidEscape: true }], // ✘ disabled by eslint-config-prettier
    radix: 'error',
    'require-atomic-updates': 'error',
    // 'require-await': 'off',
    // 'require-unicode-regexp': 'off',
    'require-yield': 'error',
    'rest-spread-spacing': 'error', // ✘ disabled by eslint-config-prettier
    semi: ['error', 'never'], // ✘ disabled by eslint-config-prettier
    'semi-spacing': 'error', // ✘ disabled by eslint-config-prettier
    // 'semi-style': 'off',
    // 'sort-imports': 'off',
    // 'sort-keys': 'off',
    // 'sort-vars': 'off',
    'space-before-blocks': 'error', // ✘ disabled by eslint-config-prettier
    'space-before-function-paren': 'error', // ✘ disabled by eslint-config-prettier
    'space-in-parens': 'error',
    'space-infix-ops': 'error', // ✘ disabled by eslint-config-prettier
    'space-unary-ops': 'error', // ✘ disabled by eslint-config-prettier
    // 'spaced-comment': 'off',
    // strict: 'off',
    'switch-colon-spacing': 'error', // ✘ disabled by eslint-config-prettier
    'symbol-description': 'error',
    'template-curly-spacing': 'error', // ✘ disabled by eslint-config-prettier
    'template-tag-spacing': 'error', // ✘ disabled by eslint-config-prettier
    'unicode-bom': 'error', // ✘ disabled by eslint-config-prettier
    'use-isnan': 'error',
    'valid-typeof': ['error', { requireStringLiterals: true }],
    'vars-on-top': 'error',
    'wrap-iife': ['error', 'any', { functionPrototypeMethods: true }], // ✘ disabled by eslint-config-prettier
    // 'wrap-regex': 'off',
    // 'yield-star-spacing': 'off',
    yoda: 'error',
  },
}
